### ISSUE TITLE
Reset des variables

### ISSUE THREAD

**Issue by Ziouda** [Jean-Bernard-Hallez/jarvis-cestquand#4]
Bonjour JB,

Merci pour ce petit plugin bien intéressant.
Je remonte un petit soucis, quelque soit le nom, j'ai le même calcul de date qui remonte

Ziad: c'est quand l'anniversaire de david
Jarvis: david fêtes ses 42 ans dans 38 jours
Ziad: c'est quand l'anniversaire de serge
Jarvis: serge fêtes ses 42 ans dans 38 jours

pourtant j'ai bien les bonnes dates dans le fichier de config
#---# 15/02/1947 l'anniversaire de SERGE
#---# 22/02/1975 l'anniversaire de DAVID

**Comment by Ziouda** [comment]
Je pense avoir trouvé @Jean-Bernard-Hallez 
J'ai ajouter cette ligne au début de ta fonction **cestpourquand()**
`lignenumero=""`

Merci,

**Comment by Jean-Bernard-Hallez** [comment]
Ok Merci @Ziouda j'ai modifié...
