### ISSUE TITLE
2 Problèmes de calcul de date

### ISSUE THREAD

**Issue by Ziouda** [Jean-Bernard-Hallez/jarvis-cestquand#6]
Hello @Jean-Bernard-Hallez 

Me revoilà avec deux nouveaux problèmes de calcul de date

Voici ce que j'ai:
Ziad: quel jour
Jarvis: nous sommes le lundi 03 avril 2017
Ziad: c'est quand l'anniversaire de jean marc
Jarvis: jean marc fêtes ses 57 ans dans 23 jours
Ziad: prochains evenements
Jarvis: le mercredi 08 avril  dans 5 jours et ça sera les 19 ans de l'anniversaire de ALLAN.
Jarvis: le jeudi 20 avril  dans 17 jours et ça sera les 50 ans de l'anniversaire de ISABELLE.
Jarvis: le samedi 22 avril  dans 19 jours et ça sera les 28 ans de l'anniversaire de JOHNNY.
Ziad: c'est quand l'anniversaire de sylvana
plugins/jarvis-cestquand/fr/functions.sh: ligne 196: [[: 09 : valeur trop grande pour la base (le symbole erroné est "09")
plugins/jarvis-cestquand/fr/functions.sh: ligne 201: [[: 09 : valeur trop grande pour la base (le symbole erroné est "09")

extract du fichier Config.sh
# MARS
#---# 09/03/1984 l'anniversaire de SYLVANA
#---# 10/03/1960 l'anniversaire de JEAN MARC

**Problème N°1:**
L'anniversaire de JEAN MARC est déjà passé "10 Mars" mais le script me dit que son prochain anniversaire est dans 23 jours

Dans les prochains événements, je n'ai pas d'anniversaire dans 23 jours

**Problème N°2:**
Erreur lorsque je souhaite avoir l'anniversaire de sylvana au 09 mars

Je vais essayé de chercher de mon coté si je trouve quelque chose

**Comment by Jean-Bernard-Hallez** [comment]
Voilà et Merci @Ziouda  C'est Corrigé... ;-)

**Comment by Ziouda** [comment]
Hello,

Merci @Jean-Bernard-Hallez pour cette réponse rapide. Très efficace, c'est super 👍 

Corrigé pour le Problème N°2 mais toujours pas bon pour le problème N°1

Ziad: c'est quand l'anniversaire de sylvana 
Jarvis: sylvana fêtes ses 33 ans dans 25 jours
Ziad: c'est quand l'anniversaire de jean marc
Jarvis: jean marc fêtes ses 57 ans dans 24 jours

#---# 09/03/1984 l'anniversaire de SYLVANA
#---# 10/03/1960 l'anniversaire de JEAN MARC

**Comment by Jean-Bernard-Hallez** [comment]
ET coucou... Je viens de rentrer et j'ai pris mon temps de tout vérifier... Ca devrait rouler comme sur des roulettes... essayes... Mecri pour ta patience... JB.

**Comment by Ziouda** [comment]
That's perfect.
Tu peux clore le sujet
