### ISSUE TITLE
Le plugin "c'est quand" ne donne pas l'âge

### ISSUE THREAD

**Issue by Clovis-krz** [Jean-Bernard-Hallez/jarvis-cestquand#7]
Bonjour,
Voici l'erreur quand je demande l'anniversaire de quelqu'un :

Moi: c'est quand l'anniversaire de BLABLA
plugins/jarvis-cestquand/fr/functions.sh: ligne 131: bc : commande introuvable
Nestor: BLABLA fêtes ses  ans dans 17 jours
Nestor: Sa date de naissance le 27 avril 2005

J'espère que vous arriverez à résoudre le problème parce que le plugin est très prometteur 👍

**Comment by Ziouda** [comment]
Bonjour Clovis

Pouvez vous vous référer au premier commentaire sur ce message et me dire si ça marche ?

https://github.com/Jean-Bernard-Hallez/jarvis-cestquand/issues/2

**Comment by Clovis-krz** [comment]
Bonjour,
Merci beaucoup de votre réponse.
Je viens de tester à l'instant et Jarvis me donne maintenant l'âge.
Encore merci :)
